<?php

declare(strict_types=1);

/*
 * Regenerates src/mimetypes.php from the Apache httpd mime.types file.
 *
 * Usage:
 *   php generate-mimetypes.php               # downloads the latest mime.types
 *   php generate-mimetypes.php mime.types    # uses a local copy
 *
 * Source (public domain, maintained by the Apache httpd project):
 *   https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
 *   https://github.com/apache/httpd/blob/trunk/docs/conf/mime.types (mirror)
 */

const SOURCE_URL = 'https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types';
const MIRROR_URL = 'https://github.com/apache/httpd/blob/trunk/docs/conf/mime.types';

$source = $argv[1] ?? SOURCE_URL;

$apacheMimeTypes = file_get_contents($source);
if (false === $apacheMimeTypes) {
    fwrite(STDERR, "Cannot read {$source}".PHP_EOL);

    exit(1);
}

$mimetypes = [];
foreach (preg_split('/\r?\n/', $apacheMimeTypes) as $line) {
    $line = trim($line);
    if ('' === $line || str_starts_with($line, '#')) {
        continue;
    }

    $matches = [];
    if (1 !== preg_match('/^(\S+)\s+(.*)$/', $line, $matches)) {
        throw new \RuntimeException("Cannot parse line {$line}");
    }

    foreach (preg_split('/\s+/', $matches[2]) as $extension) {
        $mimetypes[$extension] = $matches[1];
    }
}

// additions not (yet) part of the apache list
$mimetypes['yml'] ??= 'application/x-yaml';
$mimetypes['jsonx'] ??= 'application/jsonx+xml';

ksort($mimetypes, SORT_STRING);

$lines = [];
foreach ($mimetypes as $extension => $mimetype) {
    $lines[] = sprintf('    %s => %s,', var_export((string) $extension, true), var_export($mimetype, true));
}

$content = <<<PHP
<?php

declare(strict_types=1);

/*
 * Generated by generate-mimetypes.php - do not edit manually.
 *
 * Source: Apache httpd mime.types (public domain)
 *   %s
 *   %s (mirror)
 *
 * Generated: %s
 */

return [
%s
];

PHP;

file_put_contents(
    __DIR__.'/src/mimetypes.php',
    sprintf($content, SOURCE_URL, MIRROR_URL, date('Y-m-d'), implode(PHP_EOL, $lines))
);

echo sprintf('Wrote %d mimetypes to src/mimetypes.php', \count($mimetypes)).PHP_EOL;
